repos:
  - repo: local
    hooks:
      - id: black
        name: run black
        entry: black
        language: python
        args: ["--line-length=120"]

      - id: isort
        name: run isort
        entry: isort
        language: python
        language_version: python3


